name: Remove JMeter Report
on:
  workflow_dispatch:
    inputs:
      report_id:
        description: "Report ID to remove (e.g., 20250204-023014_ED25519_on_vm6)"
        required: true

jobs:
  remove-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove the specified report
        run: |
          cd reports
          if [ -d "${{ inputs.report_id }}" ]; then
            echo "Removing report: ${{ inputs.report_id }}"
            rm -rf "${{ inputs.report_id }}"
          else
            echo "Report not found: ${{ inputs.report_id }}"
            exit 1
          fi

      - name: Update Index File
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html><head><title>Reports</title></head><body><h1>Reports List</h1><ul>" >> index.html
          for folder in $(ls -d reports/*/ 2>/dev/null || true); do
            folder_name=$(basename $folder)
            echo "<li><a href='reports/$folder_name/index.html'>$folder_name</a></li>" >> index.html
          done
          echo "</ul></body></html>" >> index.html

      - name: Commit and Push Changes
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/GryphusID/ejbca-performance-tests.git
            git add index.html
            git add -u reports
            git commit -m "Remove report: ${{ inputs.report_id }}"
            git push origin gh-pages